tasks:
  - name: YAUS Server
    init: bash ./deploy.sh
    env:
      DATABASE_URL: "postgresql://postgres:yoursupersecret@localhost:5432/shortdb?schema=public"

ports:
  - port: 5432
    onOpen: ignore
    visibility: public
  - port: 15003
    onOpen: ignore
    visibility: public
  - port: 4369
    onOpen: ignore
    visibility: public
  - port: 5672
    onOpen: ignore
    visibility: public
  - port: 25672
    onOpen: ignore
    visibility: public
  - port: 15672
    onOpen: ignore
    visibility: public
  - port: 8088
    onOpen: ignore
    visibility: public